### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by veso266** [kitsunde/jquery-cors#2]
Hi there, it seams that I cannot use this plugin for some reason as it errors out
```
Uncaught TypeError: $.enableCORS is not a function
```
I am trying to use it like this
```html
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="js/cors.js"></script>
</head>
<body>

	<select><option>Test</option></select>
	
	<script>
	$(document).ready(function() {	
		var test_url = 'https://google.com';
		
		$.get(test_url, function(r){
			console.log(r);
		});
	});
	</script>
	
	
	<script></script>
	<script>$.enableCORS();</script>
	<script></script>
</body>
</html>
```

and use it with this proxy: https://corsproxy.io/?https://google.com 

but I cannot seam to even initialize it

So if you maybe have some idea what I am doing wrong that I cannot use this plugin?

**Comment by kitsunde** [comment]
This project hasn't been live for about 8 years. :P
